export const UNIQUAL_ID_CONSTANTS = {
  PRIVACY_ID: 'PRIVACY_ID',
  AGREEMENT_ID: 'AGREEMENT_ID',
  CONTACTS_ID: 'CONTACTS_ID',
  ABOUT_ID: 'ABOUT_ID',
  COVER_ID: 'COVER_ID',
  CLAUSE_ID: 'CLAUSE_ID',
  VOTE_ID: 'VOTE_ID',
};